# Generated by Django 3.1.6 on 2021-02-06 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_location', models.CharField(max_length=50)),
                ('destination_location', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField(auto_now=True)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=3)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('number_of_seats', models.IntegerField(default=4)),
                ('car_name', models.CharField(blank=True, max_length=100, null=True)),
                ('car_number', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driving', to=settings.AUTH_USER_MODEL)),
                ('riders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reject', 'Reject'), ('approve', 'Approve'), ('pending', 'Pending')], default='Pending', max_length=50)),
                ('comments', models.CharField(max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
                ('user_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_requested', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
