# Generated by Django 3.1.6 on 2021-02-06 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='riders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='riding', to=settings.AUTH_USER_MODEL),
        ),
    ]
