# Generated by Django 3.1.6 on 2021-02-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_auto_20210206_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='distance',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
