# Generated by Django 3.1.6 on 2021-02-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_auto_20210206_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='price',
            new_name='price_per_km',
        ),
    ]
