# Generated by Django 3.1.6 on 2021-02-06 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0005_auto_20210206_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='ride',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rides_requested', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
