# Generated by Django 3.1.6 on 2021-02-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_auto_20210206_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
