# Generated by Django 3.1.6 on 2021-02-06 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_ride_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
