# Generated by Django 3.1.6 on 2021-02-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0008_auto_20210206_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
