# Generated by Django 3.1.6 on 2021-02-07 05:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0011_auto_20210207_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('drive', 'rider')},
        ),
    ]
