# Generated by Django 3.1.6 on 2021-02-07 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_auto_20210207_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='drive',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='rides.ride'),
        ),
    ]
