# Generated by Django 3.1.6 on 2021-02-07 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0014_auto_20210207_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='rider',
            new_name='riders',
        ),
        migrations.AddField(
            model_name='trip',
            name='ride',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='rides.ride'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('ride', 'riders')},
        ),
        migrations.RemoveField(
            model_name='trip',
            name='drive',
        ),
    ]
