# Generated by Django 3.1.6 on 2021-02-07 18:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0015_auto_20210208_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='riders',
            new_name='rider',
        ),
        migrations.AlterUniqueTogether(
            name='trip',
            unique_together={('ride', 'rider')},
        ),
    ]
