# Generated by Django 3.1.6 on 2021-02-07 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0016_auto_20210208_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='driver',
        ),
        migrations.AlterField(
            model_name='request',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rides_requested', to='rides.ride'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
