# Generated by Django 3.1.6 on 2021-02-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0017_auto_20210208_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='number_of_seats_available',
            field=models.IntegerField(default=4),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='rides.ride')),
            ],
        ),
    ]
