# Generated by Django 3.1.6 on 2021-02-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0018_auto_20210208_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='number_of_seats',
            field=models.IntegerField(default=3),
        ),
    ]
