# Generated by Django 3.1.6 on 2021-02-07 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0019_auto_20210208_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='number_of_seats_available',
        ),
    ]
