# Generated by Django 3.1.6 on 2021-02-08 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0020_remove_ride_number_of_seats_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='rides.ride'),
        ),
    ]
