# Generated by Django 3.1.6 on 2021-02-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0023_auto_20210208_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
