# Generated by Django 3.1.6 on 2021-02-08 13:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rides', '0024_ride_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('ride', 'rider')},
        ),
    ]
