# Generated by Django 3.1.6 on 2021-02-08 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0025_auto_20210208_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
