# Generated by Django 3.1.6 on 2021-02-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0026_payment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='time',
            new_name='generated_time',
        ),
    ]
