# Generated by Django 3.1.6 on 2021-02-08 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0027_auto_20210208_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
